# permissions for end users to edit guutests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guutest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: swift-network
    app.kubernetes.io/part-of: swift-network
    app.kubernetes.io/managed-by: kustomize
  name: guutest-editor-role
rules:
- apiGroups:
  - guu.github.com
  resources:
  - guutests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - guu.github.com
  resources:
  - guutests/status
  verbs:
  - get
